"""Constantes del protocolo ToDus."""

XMPP_HOST = "im.todus.cu"
XMPP_PORT = 5222
MUCLIGHT_HOST = "muclight.im.todus.cu"
AUTH_VERSION_NAME = "2.1.2"
AUTH_VERSION_CODE = "30102"
BUFFER_SIZE = 1024 * 1024
KEEPALIVE_INTERVAL = 25
DEFAULT_TIMEOUT = 15